
name: Build Plugin
on: [push, pull_request]

jobs:
  pluginval:
    runs-on: ubuntu-20.04
    steps:
      - name: ssh host keys
        run: |
          mkdir ~/.ssh
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-strict: false
          persist-credentials: true
      - uses: jfrey-xx/dpf-makefile-action@v1
        with:
          target: pluginval
